/*
Copyright © 2008 FONTAINE Julie
Copyright © 2008 ABATI Mathieu
 
This file is part of Universe Viewer.

Universe Viewer is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.

Universe Viewer is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with Universe Viewer; if not, write to the Free Software
Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
 */

/**
 *@author FONTAINE Julie
 * @author ABATI Mathieu
 */

import java.io.File;
import java.util.Vector;

/*
 * SelectionManagerWindow.java
 *
 * Created on 26 mai 2008, 07:08
 */
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;



/**
 *
 * @author  bluelambda
 */
public class SelectionManagerWindow extends javax.swing.JFrame {
    
    /** Creates new form SelectionManagerWindow */
    public SelectionManagerWindow() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        SelectionTable = new javax.swing.JTable();
        InfoLabel = new javax.swing.JLabel();
        MenuBar = new javax.swing.JMenuBar();
        FileMenu = new javax.swing.JMenu();
        SaveMenu = new javax.swing.JMenuItem();

        setTitle("Selection manager");
        setBounds(new java.awt.Rectangle(0, 0, 800, 600));
        setMinimumSize(new java.awt.Dimension(100, 100));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SelectionTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Right ascension", "Declination", "Redshift", "Angular Distance", "Euclidian Position"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(SelectionTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 760, -1));

        InfoLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        InfoLabel.setText("0 quasars selected");
        getContentPane().add(InfoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 780, -1));

        FileMenu.setText("File");

        SaveMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/save.png"))); // NOI18N
        SaveMenu.setText("Save...");
        SaveMenu.setEnabled(false);
        SaveMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveMenuActionPerformed(evt);
            }
        });
        FileMenu.add(SaveMenu);

        MenuBar.add(FileMenu);

        setJMenuBar(MenuBar);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-790)/2, (screenSize.height-522)/2, 790, 522);
    }// </editor-fold>//GEN-END:initComponents

    private void SaveMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveMenuActionPerformed
        JFileChooser choice = new JFileChooser();
        
        // opening save dialog
        int retval = choice.showSaveDialog(this);
        DefaultTableModel model = (DefaultTableModel)SelectionTable.getModel();
        if(retval == JFileChooser.APPROVE_OPTION)
        {
            int replace = 0;
            String filename = choice.getSelectedFile().getAbsolutePath();
            
            // verifying if file already exists
            File f = new File(filename);
            if(f.exists())
                replace = JOptionPane.showConfirmDialog(this, "File already exists! Replace?", "Save", JOptionPane.OK_CANCEL_OPTION);
            
            // writing file
            if(replace == 0)
            {
                SaveFile.open(filename);
                for(int i=0; i<model.getRowCount(); i++)
                    SaveFile.write_txt_file(model.getValueAt(i, 1)+"\t"+model.getValueAt(i, 2)+"\t"+model.getValueAt(i, 3));
                SaveFile.close();
            }
        }
    }//GEN-LAST:event_SaveMenuActionPerformed

    public void updateTable()
    {
        Vector<Quasar> q = Environment.getQuasars();
        if(q == null)
            return;
        
        DefaultTableModel model = (DefaultTableModel)SelectionTable.getModel();
        
        // making the table empty
        while(model.getRowCount() > 0)
            model.removeRow(0);
        
        if(Quasar.getSelectedCount() == 0)  // if no quasars are selected
            SaveMenu.setEnabled(false);
        else    // some quasars are selected, adding into the table
        {
            SaveMenu.setEnabled(true);
            for(int i=0; i<q.size(); i++)
            {
                if(q.get(i).isSelected())
                {
                    Vector<Object> tmp = new Vector<Object>();
                    tmp.add(i);
                    tmp.add(new String(new Double(q.get(i).getAscension()).toString()));
                    tmp.add(new String(new Double(q.get(i).getDeclination()).toString()));
                    tmp.add(new String(new Double(q.get(i).getRedshift()).toString()));
                    tmp.add(new String(new Double(q.get(i).getAngularDist()).toString()));
                    tmp.add(new String(new Double(q.get(i).getx()).toString() +", "+ new Double(q.get(i).gety()).toString()));
                    model.addRow(tmp);
                }
            }
        }
        
        InfoLabel.setText(Quasar.getSelectedCount() + " quasars selected");
        
        SelectionTable.setModel(model);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu FileMenu;
    private javax.swing.JLabel InfoLabel;
    private javax.swing.JMenuBar MenuBar;
    private javax.swing.JMenuItem SaveMenu;
    private javax.swing.JTable SelectionTable;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
